### ISSUE TITLE
Unable to test: broken link to chrome webstore

### ISSUE THREAD

**Issue by renatoargh** [WaleedAshraf/fix-gmail#1]
Hey bro, you have a broken link to the Chrome webstore
<img width="699" alt="image" src="https://user-images.githubusercontent.com/522043/166120757-95ae412d-3085-4d2f-9bfb-a2c02096c6b1.png">

**Comment by WaleedAshraf** [comment]
@renatoargh Yes. The extension is in the approval phase. Once that is done, the link will be live. Hopefully in a few days.
I'll update it here. ;)

**Comment by WaleedAshraf** [comment]
It's live 🌮

**Comment by renatoargh** [comment]
It works 🦖 🦕
